apiVersion: v1
kind: Service
metadata:
  name: users-microservice
  namespace: ecommerce-namespace
spec:
  selector:
    app: users-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP