using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary
{   
    public class Employee
    {
        // fields
        protected int _id = 101;
        protected string _name = "Unnamed";
        protected string _location;
        protected double _salary;
        protected static string _company; // static field

        // properties
        public int Id { get => _id; set => _id = value; }
        public string Name { get => _name; set => _name = value; }
        public string Location { get => _location; set => _location = value; }
        public double Salary { get => _salary; set => _salary = value; }
        public static string Company { get => _company; set => _company = value; }

        // instance constructors
        public Employee() // parameter-less ctor // explicit
        {
            // initializing fields
            // _id = 101;
            // _name = "Unnamed";
        }
        // parameterized ctor
        // explicit // no default ctor is generated by the compiler
        public Employee(int id, string name, string location, double salary)
        {
            this._id = id; // _id // Id
            this._name = name;
            this._location = location;
            this._salary = salary;
        }
        // ctor overloading
        public Employee(int id, string name, string location)
        {
            this._id = id; // _id // Id
            this._name = name;
            this._location = location;
        }
        public Employee(int id, string name)
        {
            this._id = id;
            this._name = name;
        }

        // static constructor
        static Employee()
        {
            //Employee emp = new Employee();
            Company = "DOE";
        }

        // public methods
        public virtual void Rest() // virtual method (can be overrided if required)
        {
            Console.WriteLine("Employee is resting.");
        }
        public void Work()
        {
            Console.WriteLine("Employee is working.");
        }
    }

    public interface ISales
    {
        long GetTotalSales();
    }
}
